[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "v3-core/=lib/v3-core/contracts/",
    "v3-periphery/=lib/v3-periphery/contracts/",
    "forge-std/=lib/forge-std/src/"
]

fs_permissions = [
    { access = "read-write", path = "./addresses" }
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
