[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings corrigés pour Windows
remappings = [
    "@openzeppelin/contracts=./lib/openzeppelin-contracts/.",
    "@uniswap/v3-core=./lib/v3-core/.",
    "@uniswap/v3-periphery=./lib/v3-periphery/.",
]

fs_permissions = [
    { access = "read-write", path = "./addresses" }
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
